main:
	gcc -o main main.c bintree.c

morse2text:
	gcc -o morse2text morse_to_text/main.c morse_to_text/iterative_binary_tree.c morse_to_text/bintree.c morse_to_text/optarg.c

run:
	gcc -o main main.c replaceStr.c
	./main
tree:
	gcc -o tree bintree.c

text2morse:
	gcc -o text2morse text_to_morse/main.c text_to_morse/optarg.c
