# Copyright 2022 Felix Schladt (https://github.com/FelixSchladt)
m2t:
	gcc -o m2t morse_to_text/main.c morse_to_text/iterative_binary_tree.c morse_to_text/optarg.c

t2m:
	gcc -o t2m text_to_morse/main.c text_to_morse/optarg.c
